### ISSUE TITLE
docker环境运行一段时间后提示账号异常，需在米游社APP验证。

### ISSUE THREAD

**Issue by nantayo** [Xm798/Genshin-Dailynote-Reminder#13]
### 问题描述

在docker环境运行本仓库的最新镜像，以十分钟一次的频率检查数据，并布置了企业微信推送。近期出现状况：持续数十分钟到数小时后会突然提示账号异常，微信上推送信息为
“ERROR! 获取UID: $我的UID$ 数据失败！
账号异常！请登录米游社APP进行验证。”
***
为此做了如下尝试：
将容器重启，无效。
将容器停用，第二天重新启用。一开始正常，但一段时间后仍然失效，暂未验证是否能够自然恢复。
将config文件中的cookie信息换成别人的，正常使用，暂未验证是否一段时间后也会失效。
在异地机器上布置了同样的docker容器，状况与本地一致，且失效和恢复与本地是同步的。

### 运行环境

Docker

### 程序版本

v2.1.14

### 复现流程

正常挂机就会失效，没有发现规律。

### 完整日志

```shell
stderr: 2022-11-15 14:50:16 INFO -------------------------
stderr: 2022-11-15 14:50:16 INFO 正在获取角色信息
stderr: 2022-11-15 14:50:17 INFO 获取到国服的1个角色...
stderr: 2022-11-15 14:50:17 INFO 第1个角色，$我的角色信息$
stderr: 2022-11-15 14:50:17 ERROR 账号异常！请登录米游社APP进行验证。
stderr: 2022-11-15 14:50:18 INFO Wechat Work App 🥳
stderr: 2022-11-15 14:50:18 INFO -------------------------
stderr: 2022-11-15 14:50:18 INFO 本轮运行结束，等待下次检查...
```

**Comment by Xm798** [comment]
该问题系米游社近期升级风控等级所致，目前所有调用 API 的非官方工具都遭受到了该问题，可以尝试调低频率（但无法完全解决）。

Ref https://github.com/spencerwooo/PaimonMenuBar/issues/22 https://github.com/Le-niao/Yunzai-Bot/issues/876

**Comment by nantayo** [comment]
> 该问题系米游社近期升级风控等级所致，目前所有调用 API 的非官方工具都遭受到了该问题，可以尝试调低频率（但无法完全解决）。
> 
> Ref:
> 
> * [Data fetching not working / 数据无法更新 spencerwooo/PaimonMenuBar#22](https://github.com/spencerwooo/PaimonMenuBar/issues/22)
> * [查询体力出现米游社验证码报错 Le-niao/Yunzai-Bot#876](https://github.com/Le-niao/Yunzai-Bot/issues/876)
> * [米游社接口报错，暂时无法查询：error Le-niao/Yunzai-Bot#875](https://github.com/Le-niao/Yunzai-Bot/issues/875)

收到

**Comment by softfuttery** [comment]
> 该问题系米游社近期升级风控等级所致，目前所有调用 API 的非官方工具都遭受到了该问题，可以尝试调低频率（但无法完全解决）。
> 
> Ref:
> 
> * [Data fetching not working / 数据无法更新 spencerwooo/PaimonMenuBar#22](https://github.com/spencerwooo/PaimonMenuBar/issues/22)
> * [查询体力出现米游社验证码报错 Le-niao/Yunzai-Bot#876](https://github.com/Le-niao/Yunzai-Bot/issues/876)
> * [米游社接口报错，暂时无法查询：error Le-niao/Yunzai-Bot#875](https://github.com/Le-niao/Yunzai-Bot/issues/875)

可以加入客户端获取的UserAgent来避免这个问题吗，在之前有见过这样脚本去避免

**Comment by Xm798** [comment]
> 可以加入常用客户端获取的UserAgent来避免这个问题吗，在之前有见过这样脚本去避免

不幸的是，没什么作用。

本月 9 日的 [commit](https://github.com/Xm798/Genshin-Dailynote-Reminder/commit/ac8073231c7838514eda05e6291b50ef8564d0c8) 我更新 UA 到我目前正在使用的设备，并停用了包括 Paimon Menu Bar、披萨小助手等其他所有工具，并将频率调整到 1h 一次，但这两天还是时不时弹验证码，所以米的风控不是仅仅靠设备判定的。

**Comment by Xm798** [comment]
> 可以加入常用客户端获取的UserAgent来避免这个问题吗，在之前有见过这样脚本去避免

如果有兴趣尝试的话，UA 的代码在 [dailynotehelper/getinfo/utils.py](https://github.com/Xm798/Genshin-Dailynote-Reminder/blob/master/dailynotehelper/getinfo/utils.py) 的 33 行，可以抓包之后修改试下。另外有条件的话 63 行的 udid 也可以尝试修改下。
