### ISSUE TITLE
添加青龙支持

### ISSUE THREAD

**Issue by owwkmidream** [Xm798/Genshin-Dailynote-Reminder#3]
### 问题描述

请求添加青龙支持

**Comment by Xm798** [comment]
支持青龙调度，可能需要手动设置一下。
![image](https://github.com/Xm798/Genshin-Dailynote-Reminder/assets/48074861/8331bf76-787f-46dd-8a5c-d9b3f94c9af1)

步骤大概如下（参考我给[fansmedal写的教程](https://xiaomiku01.github.io/fansMedalHelperVersion/guide/qinglong.html)）：

1. 左侧「脚本管理」，点击右上角加号，选择“新建文件”，填写脚本名称 pull_GHR.sh，内容：
 ```sh
git clone https://github.com/Xm798/Genshin-Dailynote-Reminder
cp  Genshin-Dailynote-Reminder/dailynotereminder/config/config.example.yaml Genshin-Dailynote-Reminder/dailynotereminder/config/config.yaml
```
或者用 ssh 克隆。
2. 左侧「定时任务」，然后新建任务，名称随便填，命令填 task pull_GHR.sh, 定时规则随便填，因为这个任务只要执行一次，确定。
3. 点击右侧运行，打开日志，等待仓库拉取完成，之后禁用或者删除这个脚本。
4. 回到脚本管理，找到 Genshin-Dailynote-Reminder/dailynotereminder/config/config.yaml 文件，填写自己的配置，点击“保存”。
5. 保存后新建定时任务，名称随便填，命令填 task Genshin-Dailynote-Reminder/run_once.py, 定时规则填执行的时间，确定。

**Comment by Xm798** [comment]
哦对，第一步要安装依赖，复制以下内容，拆分依赖，安装即可。

```
pydantic==1.10.11
requests
typing_extensions
pyyaml
schedule
pytz
tzlocal
dataclasses
pysocks
colorama
```

**Comment by owwkmidream** [comment]
感谢帮助，已完成
